############################################################
# I123_sphere.mac - I123 sphere 
#
# @Date: 12/21/11 
# @Author: Sanghyeb Lee, Jens Gregor, Dustin Osborne
# @Reference: Sanghyeb Lee, Jens Gregor, Dustin Osborne, "Initial Validationof a Complete GATE MODEL of the Siemens Inveon Trimodal Imaging System", IEEE, Medical Imaging Conference, Anaheim, CA, Oct 2012
#
#############################################################


# I123 source is inside a sphere filled with water!
#/gate/world/daughters/name movsource
#/gate/world/daughters/insert sphere
#/gate/movsource/geometry/setRmax 3.91 mm      #30mm/2
#/gate/movsource/geometry/setRmin 0. mm 
#/gate/movsource/geometry/setPhiStart 0 deg
#/gate/movsource/geometry/setThetaStart 0 deg
#/gate/movsource/geometry/setDeltaPhi 360 deg
#/gate/movsource/geometry/setDeltaTheta 360 deg
#/gate/movsource/setMaterial Water
#/gate/movsource/vis/setColor blue
#/gate/movsource/vis/setVisible true

# type of source I-123
# energy type
# six decay-lines are simulated 
# from Erturk's thesis 2010
# and Comparison of Image Quality of Different Iodine Isotopes, 2007

# Gamma Rays
# Enerfy        Absolute 
# 1) 158.97 keV 83.3%
# 2) 346.35 keV 0.126%
# 3) 440.02 keV: 0.428%
# 4) 505.33 keV: 0.316%
# 5) 528.96 keV: 1.39%
# 6) 538.54 keV: 0.382%
# X-rays
# 1) 23.38 71.9%
# 2) 31.1 15.1%

#1
/gate/source/addSource I123Gamma1
/gate/source/I123Gamma1/gps/particle gamma
/gate/source/I123Gamma1/gps/energytype Mono
/gate/source/I123Gamma1/gps/monoenergy 158.97 keV
/gate/source/I123Gamma1/gps/type Volume
/gate/source/I123Gamma1/gps/shape Sphere
/gate/source/I123Gamma1/gps/radius 1 cm
/gate/source/I123Gamma1/setIntensity 0.833
/gate/source/I123Gamma1/gps/angtype iso
/gate/source/I123Gamma1/setActivity 0.00003 Ci #30 micro curi
/gate/source/I123Gamma1/gps/centre 0. 0. 0. cm
/gate/source/I123Gamma1/dump 1

#2
/gate/source/addSource I123Gamma2
/gate/source/I123Gamma2/gps/particle gamma
/gate/source/I123Gamma2/gps/energytype Mono
/gate/source/I123Gamma2/gps/monoenergy 346.35 keV
/gate/source/I123Gamma2/gps/type Volume
/gate/source/I123Gamma2/gps/shape Sphere
/gate/source/I123Gamma2/gps/radius 1 cm
/gate/source/I123Gamma2/setIntensity 0.00126
/gate/source/I123Gamma2/gps/angtype iso
/gate/source/I123Gamma2/setActivity 0.00003 Ci #30 micro curi
/gate/source/I123Gamma2/gps/centre 0. 0. 0. cm
/gate/source/I123Gamma2/dump 1

#3
/gate/source/addSource I123Gamma3
/gate/source/I123Gamma3/gps/particle gamma
/gate/source/I123Gamma3/gps/energytype Mono
/gate/source/I123Gamma3/gps/monoenergy 440.02 keV
/gate/source/I123Gamma3/gps/type Volume
/gate/source/I123Gamma3/gps/shape Sphere
/gate/source/I123Gamma3/gps/radius 1 cm
/gate/source/I123Gamma3/setIntensity 0.00428
/gate/source/I123Gamma3/gps/angtype iso
/gate/source/I123Gamma3/setActivity 0.00003 Ci #30 micro curi
/gate/source/I123Gamma3/gps/centre 0. 0. 0. cm
/gate/source/I123Gamma3/dump 1

#4
/gate/source/addSource I123Gamma4
/gate/source/I123Gamma4/gps/particle gamma
/gate/source/I123Gamma4/gps/energytype Mono
/gate/source/I123Gamma4/gps/monoenergy 505.33 keV
/gate/source/I123Gamma4/gps/type Volume
/gate/source/I123Gamma4/gps/shape Sphere
/gate/source/I123Gamma4/gps/radius 1 cm
/gate/source/I123Gamma4/setIntensity 0.00316
/gate/source/I123Gamma4/gps/angtype iso
/gate/source/I123Gamma4/setActivity 0.00003 Ci #30 micro curi
/gate/source/I123Gamma4/gps/centre 0. 0. 0. cm
/gate/source/I123Gamma4/dump 1

#5
/gate/source/addSource I123Gamma5
/gate/source/I123Gamma5/gps/particle gamma
/gate/source/I123Gamma5/gps/energytype Mono
/gate/source/I123Gamma5/gps/monoenergy 528.96 keV
/gate/source/I123Gamma5/gps/type Volume
/gate/source/I123Gamma5/gps/shape Sphere
/gate/source/I123Gamma5/gps/radius 1 cm
/gate/source/I123Gamma5/setIntensity 0.0139
/gate/source/I123Gamma5/gps/angtype iso
/gate/source/I123Gamma5/setActivity 0.00003 Ci #30 micro curi
/gate/source/I123Gamma5/gps/centre 0. 0. 0. cm
/gate/source/I123Gamma5/dump 1

#6
/gate/source/addSource I123Gamma6
/gate/source/I123Gamma6/gps/particle gamma
/gate/source/I123Gamma6/gps/energytype Mono
/gate/source/I123Gamma6/gps/monoenergy 538.54 keV
/gate/source/I123Gamma6/gps/type Volume
/gate/source/I123Gamma6/gps/shape Sphere
/gate/source/I123Gamma6/gps/radius 1 cm
/gate/source/I123Gamma6/setIntensity 0.00382
/gate/source/I123Gamma6/gps/angtype iso
/gate/source/I123Gamma6/setActivity 0.00003 Ci #30 micro curi
/gate/source/I123Gamma6/gps/centre 0. 0. 0. cm
/gate/source/I123Gamma6/dump 1

#7
/gate/source/addSource I123Gamma7
/gate/source/I123Gamma7/gps/particle gamma
/gate/source/I123Gamma7/gps/energytype Mono
/gate/source/I123Gamma7/gps/monoenergy 27.38 keV
/gate/source/I123Gamma7/gps/type Volume
/gate/source/I123Gamma7/gps/shape Sphere
/gate/source/I123Gamma7/gps/radius 1 cm
/gate/source/I123Gamma7/setIntensity 0.719
/gate/source/I123Gamma7/gps/angtype iso
/gate/source/I123Gamma7/setActivity 0.00003 Ci #30 micro curi
/gate/source/I123Gamma7/gps/centre 0. 0. 0. cm
/gate/source/I123Gamma7/dump 1

#8
/gate/source/addSource I123Gamma8
/gate/source/I123Gamma8/gps/particle gamma
/gate/source/I123Gamma8/gps/energytype Mono
/gate/source/I123Gamma8/gps/monoenergy 31.1 keV
/gate/source/I123Gamma8/gps/type Volume
/gate/source/I123Gamma8/gps/shape Sphere
/gate/source/I123Gamma8/gps/radius 1 cm
/gate/source/I123Gamma8/setIntensity 0.151
/gate/source/I123Gamma8/gps/angtype iso
/gate/source/I123Gamma8/setActivity 0.00003 Ci #30 micro curi
/gate/source/I123Gamma8/gps/centre 0. 0. 0. cm
/gate/source/I123Gamma8/dump 1
