############################################
# SPECTIQ      .mac                        #
############################################
# @Date: 12/21/11 
# @Author: Sanghyeb Lee, Jens Gregor, Dustin Osborne
# @Reference: Sanghyeb Lee, Jens Gregor, Dustin Osborne, "Initial Validationof a Complete GATE MODEL of the Siemens Inveon Trimodal Imaging System", IEEE, Medical Imaging Conference, Anaheim, CA, Oct 2012
#
#############################################################
# downsized NEMA Imag Quality Phantom for SPECT #
############################################

#############################
##Main Body
#############################
/gate/world/daughters/name Body
/gate/world/daughters/insert cylinder
/gate/Body/geometry/setRmax 11.7250  mm # 23.45mm/2
/gate/Body/geometry/setRmin 10.5 mm       # 21.0mm/2
/gate/Body/geometry/setHeight 29.6 mm  # 2.1 mm + 6.5 mm + 21 +2.1 mm
/gate/Body/setMaterial Polyethylene
/gate/Body/vis/setColor blue
/gate/Body/vis/forceWireframe
/gate/Body/geometry/setPhiStart 90 deg
/gate/Body/geometry/setDeltaPhi 180 deg

###Main Body -- Upper part  --just cylinder containing activity
/gate/world/daughters/name upper
/gate/world/daughters/insert cylinder
/gate/upper/geometry/setRmax 10.5 mm # 21.0 mm/2
/gate/upper/geometry/setRmin 0  mm # full cylinder
/gate/upper/geometry/setHeight 21 mm  # 21 mm 
/gate/upper/setMaterial Air
/gate/upper/vis/setColor yellow
/gate/upper/vis/forceWireframe
/gate/upper/geometry/setPhiStart 90 deg
/gate/upper/geometry/setDeltaPhi 180 deg
/gate/upper/placement/setTranslation 0 0 4.3 mm  

###Main body --- Upper part -- Top Cover
/gate/world/daughters/name upper_top
/gate/world/daughters/insert cylinder
/gate/upper_top/geometry/setRmax 10.5 mm # 10 mm/2
/gate/upper_top/geometry/setRmin 0  mm # full cylinder
/gate/upper_top/geometry/setHeight 2.1 mm  # 2.1 mm 
/gate/upper_top/setMaterial Polyethylene
/gate/upper_top/vis/setColor green
/gate/upper_top/vis/forceWireframe
/gate/upper_top/placement/setTranslation 0 0 13.75 mm 
/gate/upper_top/geometry/setPhiStart 90 deg
/gate/upper_top/geometry/setDeltaPhi 180 deg

##Main body --- Upper part -- Water Cylinder (COLD SPOT)
/gate/world/daughters/name water_cylinder
/gate/world/daughters/insert cylinder
/gate/water_cylinder/geometry/setRmax 2.8 mm # 5.6 mm/2
/gate/water_cylinder/geometry/setRmin 0  mm # full cylinder
/gate/water_cylinder/geometry/setHeight 9.8 mm  # 3 mm 
/gate/water_cylinder/setMaterial Air
/gate/water_cylinder/vis/setColor cyan
/gate/water_cylinder/vis/forceWireframe
/gate/water_cylinder/placement/setTranslation 0 -4.9 7.8 mm 
/gate/water_cylinder/geometry/setPhiStart 90 deg
/gate/water_cylinder/geometry/setDeltaPhi 180 deg

##Main body --- Uppser part -- Air Cylinder (COLD SPOT)
/gate/world/daughters/name air_cylinder
/gate/world/daughters/insert cylinder
/gate/air_cylinder/geometry/setRmax 2.8 mm # 8 mm/2
/gate/air_cylinder/geometry/setRmin 0  mm # full cylinder
/gate/air_cylinder/geometry/setHeight 9.8 mm  # 3 mm 
/gate/air_cylinder/setMaterial Water
/gate/air_cylinder/vis/setColor white
/gate/air_cylinder/vis/forceWireframe
/gate/air_cylinder/placement/setTranslation 0 4.9 7.8 mm 
/gate/air_cylinder/geometry/setPhiStart 90 deg
/gate/air_cylinder/geometry/setDeltaPhi 180 deg

##Main Body -- cylinder 
###Main Body -- Lower part
/gate/Body/daughters/name lower
/gate/Body/daughters/insert cylinder
/gate/lower/geometry/setRmax 10.5 mm           #21.0mm/2
/gate/lower/geometry/setRmin 0 mm #full
/gate/lower/geometry/setHeight 6.5 mm      
/gate/lower/setMaterial Polyethylene
/gate/lower/vis/setColor red
/gate/lower/vis/forceWireframe
/gate/lower/placement/setTranslation 0 0 -9.45 mm



### Main Body Lower part -- hole1
### diameter 1mm 
/gate/world/daughters/name lower_hole1 
/gate/world/daughters/insert cylinder
/gate/lower_hole1/geometry/setRmax 0.3750 mm    # 0.75/2
/gate/lower_hole1/geometry/setRmin 0 mm #full
/gate/lower_hole1/geometry/setHeight 6.5 mm      
/gate/lower_hole1/setMaterial Air
/gate/lower_hole1/vis/setColor yellow
/gate/lower_hole1/vis/forceSolid
/gate/lower_hole1/placement/setTranslation 0 4.9 -9.45 mm


### Main Body Lower part -- hole2
### diameter 1mm rotated by z axis by 72 degree
/gate/world/daughters/name lower_hole2
/gate/world/daughters/insert cylinder
/gate/lower_hole2/geometry/setRmax 0.5 mm          # 1.0/2
/gate/lower_hole2/geometry/setRmin 0 mm #full
/gate/lower_hole2/geometry/setHeight 6.5 mm    
/gate/lower_hole2/setMaterial Air
/gate/lower_hole2/vis/setColor yellow
/gate/lower_hole2/vis/forceSolid
/gate/lower_hole2/placement/setTranslation 4.6602 1.5142 -9.45 mm

### Main Body Lower part -- hole3
### diameter 1mm rotated by z axis by 72*2 degree
/gate/world/daughters/name lower_hole3
/gate/world/daughters/insert cylinder
/gate/lower_hole3/geometry/setRmax 0.75 mm          # 1.5/2
/gate/lower_hole3/geometry/setRmin 0 mm #full
/gate/lower_hole3/geometry/setHeight 6.5 mm       
/gate/lower_hole3/setMaterial Air
/gate/lower_hole3/vis/setColor yellow
/gate/lower_hole3/vis/forceSolid
/gate/lower_hole3/placement/setTranslation 2.8801 -3.9642 -9.45 mm


### Main Body Lower part -- hole4
### diameter 1mm rotated by z axis by 72*3 degree
/gate/world/daughters/name lower_hole4
/gate/world/daughters/insert cylinder
/gate/lower_hole4/geometry/setRmax 0.175 mm          # 0.35/2
/gate/lower_hole4/geometry/setRmin 0 mm #full
/gate/lower_hole4/geometry/setHeight 6.5 mm      
/gate/lower_hole4/setMaterial Air
/gate/lower_hole4/vis/setColor yellow
/gate/lower_hole4/vis/forceSolid
/gate/lower_hole4/placement/setTranslation -2.8801 -3.9642 -9.45 mm

### Main Body Lower part -- hole5
### diameter 1mm rotated by z axis by 72*4 degree
/gate/world/daughters/name lower_hole5
/gate/world/daughters/insert cylinder
/gate/lower_hole5/geometry/setRmax 0.25 mm          # 0.5/2
/gate/lower_hole5/geometry/setRmin 0 mm #full
/gate/lower_hole5/geometry/setHeight 6.5 mm       
/gate/lower_hole5/setMaterial Air
/gate/lower_hole5/vis/setColor yellow
/gate/lower_hole5/vis/forceSolid
/gate/lower_hole5/placement/setTranslation -4.6602 1.5142 -9.45 mm


## Main Body Lower part -- bottom hle
## diameter 20mm at the bottom
/gate/world/daughters/name lower_bottom
/gate/world/daughters/insert cylinder
/gate/lower_bottom/geometry/setRmax 7 mm           #14.0mm/2
/gate/lower_bottom/geometry/setRmin 0 mm #full
/gate/lower_bottom/geometry/setHeight 2.1 mm       #3
/gate/lower_bottom/setMaterial Air
/gate/lower_bottom/vis/setColor yellow
/gate/lower_bottom/vis/forceSolid
/gate/lower_bottom/placement/setTranslation 0 0 -13.65 mm

/gate/world/daughters/name bottom
/gate/world/daughters/insert cylinder
/gate/bottom/geometry/setRmax 11.7250 mm # 33.5 mm/2
/gate/bottom/geometry/setRmin 0  mm # full cylinder
/gate/bottom/geometry/setHeight 3.5 mm  # 30 mm 
/gate/bottom/setMaterial PMMA
/gate/bottom/vis/setColor blue
/gate/bottom/vis/forceSolid
/gate/bottom/placement/setTranslation 0 0 -17.150 mm





